baseURL = 'https://woosang.io'
languageCode = 'en-us'
title = 'Woosang'

# Modules
[module]
  [[module.imports]]
    path = "github.com/colorchestra/smol"

# Parameters
[params]
    subtitle = "Scribbles and struggles"
    dateFmt = "01/02 2006 15:04"
	favicon = "favicon.ico"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/paul-kang-1"
        weight = 1

	[[menu.footer]]
		name = "Youtube"
		url = "https://youtube.com/@singing-nuggies"
		weight = 2

# Extra config
[markup.goldmark.renderer]
  unsafe = true
